dirk-thomas/vcstool

vcstool/clients/git.py, vcstool/executor.py
Replaces #8.
It fixes the export command when the repo has multiple remotes without requiring complex parsing of the git output.
Additionally when using `--exact` the patch will prefer `origin` / `upstream` remotes when the hash is available for them. That is a "better" behavior than picking the first available remote (in alphabetical order) containing the hash.
@jbohren @NikolausDemmel FYI
=> fix export with multiple remotes

vcstool/clients/git.py
Before `git import` was doing a `pull --rebase <remote> <ref>`. But that is only reasonable in very few use cases. Commonly if a user calls `import` the expectation is that the repository afterwards is at the specified `ref`.
Local modification should still be kept.
If the local HEAD is e.g. detached it should still switch to the new `ref` and print the standard git warning about unconnected commits (like "Warning: you are leaving 1 commit behind, not connected to
any of your branches: ...").
=> change git import behavior

vcstool/clients/bzr.py, vcstool/clients/git.py, vcstool/clients/hg.py, vcstool/commands/import_.py
If a different repository exists in a directory the `--force` option can be used to remove it before cloning the new repository. Without the option the command failed for that repository.
=> add --force option to import verb

vcstool/commands/import_.py, vcstool/executor.py
If the imported repositories contains nested folders (see #40 for an example) this patch processes them sequentially: first import the repository into the parent folder, then import the next repository into a subfolder.
=> process subfolders sequentially

vcstool/executor.py
Fix regression of #41.
The executor can't rely on `depends` to be a job attribute. It is only available for the import command.
=> fix regression of added dependencies

vcstool/commands/command.py, vcstool/commands/custom.py, vcstool/commands/export.py, vcstool/commands/import_.py, vcstool/crawler.py
Fixes #57.
Since the crawling for potentially nested repos might inflict a significant overhead it is better to require an explicit option.
=> optionally consider nested repos

vcstool/clients/git.py, vcstool/commands/import_.py
Only used for `git` since e.g. `hg` and `svn` seem to pull in subrepos / externals automatically.
=> add import --recursive option for git submodules

test/reimport.txt, test/test_commands.py, vcstool/clients/git.py
As noted in the comment, this fixes a hard failure right now when you try to import on top of an existing repo with multiple remotes, but could be made more robust by checking off against each remote in the list instead of just the first.
Example of how it breaks right now:
```
$ vcs import src < src/delphyne_gui/delphyne.repos
=== src/delphyne (git) ===
Could not determine remote url: error: invalid key (newline): remote.origin
stonier.url
=== src/delphyne_gui (git) ===
Could not determine remote url: error: invalid key (newline): remote.origin
stonier.url
```
In those repos:
```
./src/delphyne$ git remote show
origin
stonier
```
With some extra debugging to show what is getting captured by `_get_url`:
```
$ vcs import src < src/delphyne_gui/delphyne.repos
Running command …
```
=> Avoid unnecessary failure when a git repo has multiple remotes

vcstool/clients/svn.py
Fixes #69.
The calling code always passes a string, see https://github.com/dirk-thomas/vcstool/blob/b6d5f5f2e7be6519d23420e8f677dbdae0f58839/vcstool/commands/import_.py#L143
=> fix usage of version with svn import

stdeb.cfg
See ros-infrastructure/catkin_pkg#232 why dropping these EOL distros is necessary to allow releasing Debian packages on current Ubuntu distros.
=> remove Ubuntu pre-Trusty and Debian Wheezy

vcstool/commands/import_.py
required for https://github.com/ros-infrastructure/ros_buildfarm/pull/574
=> [import] don't fail on empty repositories list, print 'warning' instead

test/test_flake8.py
Otherwise new warnings which are by default ignore won't be ignored when a custom set is passed.
=> flake8: use --extend-ignore to use defaults

vcstool/clients/git.py
As it stands, if `vcs export` is attempted on a repository that is targeting a ref that is tagged but is not part of any branches, an error will occur:
```
<REPO>: Could not determine remote containing '<REF>'
```
=> Support export of refs that are only part of tags

test/test_flake8.py
The API was removed in [flake 3.7.0](https://github.com/PyCQA/flake8/blob/59fdc5250c9166f40217172bd53a430eb666f683/docs/source/release-notes/3.7.0.rst):
> Remove broken and unused `flake8.listen` plugin type
=> remove make_notifier() call which has been removed from the flake8 API

setup.py
argparse is part of the standard library since Python 2.7
This was discovered when a stray argparse dependency showed up during RPM packaging when the dependencies were extracted from the package.
=> Fix argparse requirement for Python 2.7

vcstool/commands/import_.py
To avoid the following warning with newer `yaml` versions (which also fails CI):
> YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
=> use yaml.safe_load

test/list2.repos, test/validate2.txt, vcstool/clients/hg.py, vcstool/clients/svn.py, vcstool/commands/command.py
Replaces #95.
Fixes regression introduced in https://github.com/dirk-thomas/vcstool/pull/90/files#diff-ab1fa1c2a07801d2a7ab588a990f0879L72
Instead of adding the argument `path` or `paths` with its string or list of strings default value the patch introducing the regression always added a `path` argument.
=> fix regressions with path/paths arguments

test/test_commands.py, vcstool/clients/git.py, vcstool/commands/import_.py
This makes `import --force` overwrite directories, even if they're not empty and not a git repository. I have only tested this with `git`. I haven't checked the other clients, so I don't know if they're also affected.
=> import `--force` should overwrite non-empty directories

vcstool/clients/hg.py
Without this fix, a failed checkout will print a vcstool internal error:
```
=== src/ign-common (hg) ===
Invocation of command 'import' on client 'hg' failed: UnboundLocalError: local variable 'result_clone' refer
enced before assignment (/usr/local/lib/python3.6/dist-packages/vcstool/clients/hg.py:169) 
```
With the fix, we get the desired message, in my case:
```
=== src/ign-common (hg) ===
Could not checkout 'custom_paths_uri': abort: uncommitted changes
(commit or update --clean to discard changes)
```
=> Fix output on failed checkout

.travis.yml
PyYAML 5.3+ only supports Python 3.5+.
=> pin PyYAML version for Python 3.4

README.rst
Document the `--workers` options in combination when needing `stdin`.
Related to #23 and #26.
=> add section about parallelization and stdin

README.rst
I had to update the key fingerprint because the ROS repo uses a different one:
```
Hit:1 https://download.docker.com/linux/debian buster InRelease
Hit:2 https://nvidia.github.io/libnvidia-container/debian10/amd64  InRelease                                                                                                     
Hit:3 https://nvidia.github.io/nvidia-container-runtime/debian10/amd64  InRelease                                                                                                
Hit:4 http://security.debian.org/debian-security buster/updates InRelease                                                                                                        
Hit:5 https://nvidia.github.io/nvidia-docker/debian10/amd64  InRelease …
```
=> Update key fingerprint in README

test/log_limit.txt, vcstool/clients/git.py, vcstool/clients/hg.py, vcstool/commands/log.py
This changes the default for `git` to `--pretty=short` which still shows the commit hash, author, (merge), and title but not the date and the full commit message anymore.
For `hg` is doesn't change the default but `--verbose` allows showing the list of changed files and the full commit message.
=> add log --verbose option

vcstool/commands/import_.py
e.g.
```
echo 'repositories: {somedir: {type: git}}' | vcs import .
Traceback (most recent call last):
File "/home/dan/.local/bin/vcs", line 11, in <module>
load_entry_point('vcstool', 'console_scripts', 'vcs')()
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/vcs.py", line 26, in main
return entrypoint(args)
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/import_.py", line 186, in main
repos = get_repositories(args.input)
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/import_.py", line 67, in get_repositories
return get_repos_in_vcstool_format(repositories)
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/import_.py", line 90, in get_repos_in_vcstool_format
repo['url'] = attributes['url']
KeyError: 'url'
```
versus
```
echo …
```
=> Fix crashes due to catching AttributeError instead of KeyError

vcstool/commands/import_.py
previously:
```
echo 'repositories: {somedir: {type: foo, url: aoeu}}' | vcs import .
Traceback (most recent call last):
File "/home/dan/.local/bin/vcs", line 11, in <module>
load_entry_point('vcstool', 'console_scripts', 'vcs')()
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/vcs.py", line 26, in main
return entrypoint(args)
File "/home/dan/Documents/colcon/src/vcstool/vcstool/commands/import_.py", line 203, in main
url = job['command'].url
AttributeError: 'NoneType' object has no attribute 'url'
```
now:
```
echo 'repositories: {somedir: {type: foo, url: aoeu}}' | vcs import .
=== ./somedir (none) ===
Repository type 'foo' is not supported
```
=> Fix unsupported repo type crash

test/import.txt, test/test_commands.py
While still being compatible with older git versions.
Not pretty - but at least that makes the tests pass on e.g. Ubuntu Focal.
=> update expected output in tests for newer git version

.github/workflows/ci.yml
Using GitHub action workflow to run CI on:
* Ubuntu with all targeted Python versions
* except 3.4 which is not supported by GitHub action, keeping Travis CI around while Debian Jessie with Python 3.4 is targeted
* macOS with the latest Python release (atm 3.8)
* Windows with the latest Python release (atm 3.8)
=> add GitHub action workflow

test/test_commands.py, vcstool/clients/bzr.py, vcstool/clients/git.py, vcstool/clients/hg.py, vcstool/clients/tar.py, vcstool/clients/zip.py, vcstool/util.py
The first commit fixes #130 and fixes ros2/ci#200. It makes sure that files/directories which are hidden can be deleted by non-admin users. This replaces #129.
The second commit handles a problem in the tests which determines the git version. On Windows the reported string might contain a version component "windows".
=> fix issues on Windows

vcstool/clients/git.py
This bug occurs only when you have file and branch on remote with the same name, because if `git checkout` don't find local branch then resets file with this name.
1. Make a file `foo` and commit it
2. Make a branch `foo` and push it to remote
3. Use vcs tool with config:
```
repositories:
repo:
type: git
url: git@gitlab.com:foo/bar/repo.git
version: foo
```
4. In results, downloaded repository has branch `master` not `foo` 
According to https://git-scm.com/docs/git-checkout adds a double dash is enough
PS. thanks to @ksuszka to found the bug!
=> add double dash to move to another branch, not reset file/directory in git client

test/log_limit.txt, vcstool/clients/git.py
Before:
> commit 9de5d881774a25f37de2f8ca3fd7afc9230a1e4d
With `--decorate`:
> commit 9de5d881774a25f37de2f8ca3fd7afc9230a1e4d (HEAD -> master, origin/master, origin/HEAD)
=> always --decorate git log

test/test_commands.py
git 2.27.0 warns when pulling with a default config. See: https://github.com/git/git/blob/master/Documentation/RelNotes/2.27.0.txt#L22-L25
This updates the tests to handle this warning message.
Fixes #145
The fix could be a bit prettier, but I tried to follow the existing conventions in the test file.
=> Fix test_pull*() for git>=2.27.0

vcstool/commands/import_.py, vcstool/commands/validate.py
Follow up of https://github.com/dirk-thomas/vcstool/pull/123#discussion_r410405443 to improve how the default values are shown in the help messages.
=> use dash instead of stdin as default

test/pull.txt, test/test_commands.py, vcstool/clients/git.py
Supports one use case described in #165.
=> gracefully warn about inability to pull detached HEAD instead of fail

vcstool/commands/log.py
As pointed out in https://github.com/dirk-thomas/vcstool/pull/173#issuecomment-713880501 and as admitted in https://github.com/dirk-thomas/vcstool/pull/173#issuecomment-713882745, the author of this PR misunderstood the expected behavior of `vcs log --limit-tag`. While help message describes the behavior correctly, wording may be a bit subtle and could signify the meaning to avoid misunderstanding.
<details><summary>Previous OP for the record</summary>
`vcs log --limit-tag` seems to ignore the tag it receives.
Using today's `vcstool` repo, the cmd in quetion looks always returning the latest head on the current branch.
```
=== . (git) ===
commit ff8ce2638a17a80e3ee303db502b27e1d7dabdcf (HEAD -> master, origin/master, origin/HEAD)
Author: Dirk Thomas <dirk-thomas@users.noreply.github.com> …
```
=> [log] Clarify the behavior of --limit-*tag* options 

.travis.yml, README.rst, scripts/vcs, scripts/vcs-branch, scripts/vcs-bzr, scripts/vcs-custom, scripts/vcs-diff, scripts/vcs-export, scripts/vcs-git, scripts/vcs-help, scripts/vcs-hg, scripts/vcs-import, scripts/vcs-log, scripts/vcs-pull, scripts/vcs-push, scripts/vcs-remotes, scripts/vcs-status, scripts/vcs-svn, scripts/vcs-validate, setup.py, stdeb.cfg
While Python 3.5 is also EOL this package continues to support it atm to continue targeting Ubuntu Xenial.
Since Debian Jessie Long Term Support has ended in June 2020 it is being removed as a targeted platform.
=> drop Python 2.7 and <= 3.4 support, Debian Jessie

.github/workflows/ci.yml
=> remove Python 2.7 from GitHub workflow

README.rst, publish-python.yaml, stdeb.cfg
Add `publish-python.yaml` for future Python 3 releases to packagecloud.io and PyPI.
=> publish-python.yaml, future Python 3 releases to packagecloud.io and PyPI

vcstool/clients/git.py
Separated from #180.
The `git --version` output on macOS might look like this which wasn't supported until this patch:
> `git version 2.24.3 (Apple Git-128)`
=> fix git version detection on macOS

.github/workflows/ci.yml
As recommended in https://github.com/dirk-thomas/vcstool/pull/180#issuecomment-717792626 to be on the safe side in case either of the packages is already installed.
=> always use --upgrade for pip install

README.rst
Using sudo directly with `pip` is considered a bad practice in the python community, since  it's rarely actually needed, it may mess up file permissions and it can actually break `pip` if used incorrectly:
See following links for more details:
- https://github.com/pypa/pip/issues/5495
- https://askubuntu.com/a/1149202/305258
Also using sudo in this case, is unnecessary since we're operating in development mode (i.e., not copying the file contents systemwide)
=> Don't use sudo with pip

README.rst, setup.py, vcstool-completion/vcs.fish, vcstool/commands/help.py
Current PR adds the following:
A fish autocompletion file and the `--commands-descriptions` flag for printing the vcs subcommands in a tab-separated list along with their descriptions 
~* A small change in the README suggesting the use of `pip -e` instead of `sudo python setup.py` for installing in dev mode~
~* Minor reformatting in the flow control of the CLI parsing~
Here's how the autocompletion looks in fish now:
=> Add fish autocompletion

test/test_commands.py
Split-up test_validate() into two parts:
* test_validate: Part requires only git (subtest 1 and subtest 3)
* test_validate2: Part requires subversion (svn) and mercurial (hg) (former middle part = subtest 2)
* test_validate2 is skipped if either svn or hg are not installed 
(skip logic was manually tested: with svn and hg, with svn, with hg, without svn and without hg).
* support: FAKE-PROGRAM detection that exist (svn)
but only states that the program is missing if it is run
(usecase: macOS for svn that was a former part of Xcode).
HINT: PR #181 works for me (in my workspace).
=> allow some tests (except on CI) to be skipped when svn/hg are unavailable

test/log_merges_only.txt, test/test_commands.py, vcstool/clients/git.py, vcstool/commands/log.py
See https://github.com/dirk-thomas/vcstool/issues/174
```
=== . (git) ===
commit d82cb6ec3be31533dc90979e083072c6440c68d3
Merge: dcee1a0 c174cd8
Author: Dirk Thomas <dirk-thomas@users.noreply.github.com>
Merge pull request #61 from dirk-thomas/use_pytest
commit 68a2451d33c4f4de6f148de57439f08f0330d898
Merge: f7f008a 93eb8c6
Author: Dirk Thomas <dirk-thomas@users.noreply.github.com>
Merge pull request #58 from dirk-thomas/support_nested_repos
commit f7f008a1279dce9b213c9cfc9e72a2f1fbf73c33
Merge: 3d98c90 3d8d011
Author: Dirk Thomas <dirk-thomas@users.noreply.github.com>
Merge pull request #59 from dirk-thomas/flake8
```
- This PR at the time of writing just adds a simple wrapper for underlining `vcs` tool, without new advantage. The design with `custom` verb to delegate commands to each …
=> [log] merge-only option

vcstool/executor.py
Closes #202
The real problem is that some special shells on Windows may not support backslashes at all.
* PowerShell supports mixed slashes
* CMD mostly doesn't
* bash (installed along with Git for Windows) only supports forward slashes
I've tried to find a simple method to detect special shells like this, since we preferably only want to change the current behaviour for those shells, although it's okay to change the behaviour for shells that support mixed styles. I looked into `MSYSTEM` but ultimately found that checking if `$_` exists and contains a forward slash seems to work fine.
> **Special Parameters**
> **_**
> At shell startup, set to the absolute pathname used to invoke the shell or shell script being executed as passed in the environment or argument list. Subsequently, expands …
=> Detect special POSIX shells on Windows and output POSIX paths

README.rst
Closes #224
This updates the instructions for adding the ROS repository key to the most recent instructions here: http://wiki.ros.org/noetic/Installation/Ubuntu#Installation.2FUbuntu.2FSources.Set_up_your_keys.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
=> Update ROS repository key instructions

.github/workflows/ci.yml, test/test_commands.py
There was a strategy matrix, but all jobs were running on `ubuntu-latest`.
Tests run fine on macOS if I set `advice.detachedHead` to `true` (I think it's off by default on newer git versions, and macOS has a more recent version).
For Windows, it's a bit more complicated because of the different path separator. It required some more manual adjustments to the test code.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
=> Make CI jobs use matrix.os value and fix tests for macOS & Windows
