vcstool/commands/export.py
=> improve output of export command in case of errors

vcstool/executor.py
Skip repos which show "same repo" message when passing `--hide`.
=> don't show 'same repo' when using --hide

vcstool/clients/git.py
=> do not hide git status when ahead or behind

vcstool/commands/import_.py
Fixes another regression of #41 and fixes #43.
=> fix exit condition in loop

vcstool/commands/command.py
=> choose default parallel workers based on cpu count

README.rst, test/clients.txt, test/import.txt, test/list.repos, test/test_commands.py, vcstool/clients/__init__.py, vcstool/clients/tar.py, vcstool/clients/vcs_base.py, vcstool/clients/zip.py
=> support zip

test/status.txt, test/test_commands.py, vcstool/clients/bzr.py, vcstool/clients/git.py, vcstool/clients/hg.py, vcstool/clients/svn.py, vcstool/clients/tar.py, vcstool/clients/vcs_base.py, vcstool/clients/zip.py, vcstool/commands/import_.py
=> add --retry option to import verb

vcstool/commands/import_.py
Address problem when version is number and not quoted in yaml.
=> ensure to interpret version as string

test/test_flake8.py, vcstool/commands/help.py
Any yet another update to match changes to the API.
=> update to work with latest flake8

.travis.yml, test/import.txt, test/pull.txt, test/status.txt, test/test_commands.py
Use `pytest` to run the tests since it provides much better introspection in case tests fail.
=> use pytest on Travis

setup.py, stdeb.cfg
=> add explicit dependency on setuptools

vcstool/clients/hg.py
hg wasn't using noninteractive, so a computer without keyring set up would just hang.
=> make hg use non interactive

README.rst
=> add note about vcstools

.travis.yml, test/test_commands.py, vcstool/commands/branch.py, vcstool/commands/custom.py, vcstool/commands/diff.py, vcstool/commands/export.py, vcstool/commands/help.py, vcstool/commands/import_.py, vcstool/commands/log.py, vcstool/commands/pull.py, vcstool/commands/push.py, vcstool/commands/remotes.py, vcstool/commands/status.py, vcstool/commands/vcs.py, vcstool/executor.py, vcstool/streams.py
=> expose API to provide custom streams

vcstool/clients/git.py
=> support --recursive for import on existing working copy

vcstool/clients/git.py
=> fix import --recursive in combination with non-default branch

vcstool/commands/export.py
=> fix export path for nested repos when . contains a repo

test/export_exact.txt, vcstool/clients/git.py
=> export unique tag names when applicable

test/reimport_skip.txt, test/test_commands.py, vcstool/clients/git.py
=> also --skip-existing for entries with a version

vcstool/commands/import_.py
When calling `import` with SSH repository URLs and an unknown host `ssh` interactively requests confirmation of the fingerprint. When multiple workers are used it is not possible to answer that prompt. This patch makes the `import` command fall back to a single worker if SSH urls are detected and the host is unknown (based on the rc of the `ssh-keygen -F` command).
Fixes #110.
=> fallback to single worker when importing from unknown hosts

vcstool/clients/svn.py
=> fix string substitution for error message in SVN

vcstool/clients/git.py, vcstool/commands/import_.py
=> skip existing non-git directories with --skip-existing

test/test_commands.py
This makes the tests run cleanly on RHEL 7.
Tested for regressions on Fedora 32 with git 2.26.2.
=> Make tests compatible with git back to 1.8.3.1

test/test_flake8.py, vcstool/clients/git.py
Fixes #139 
Similar to ament/ament_lint#242.
=> support flake8 3.8

test/test_commands.py
=> fix logic in test since the commands are expected to have a return code of zero

README.rst, vcstool/commands/import_.py
Some minor text-related fixes.
=> Fix text-related typos/mistakes and improve consistency

vcstool/clients/git.py
Fixes #151 which is a regression introduced by #147.
=> fix ls-remote handling of lines like a banner

README.rst
Based on the feedback in https://github.com/dirk-thomas/vcstool/pull/147#issuecomment-643606660
=> mention default value of version key

vcstool/clients/git.py
Follow up of #154. Fixes #157.
=> filter ls-remote output everywhere

vcstool/clients/git.py
=> fix importing git with hash used for non-standard reference

test/test_commands.py, vcstool/clients/git.py
=> fix import with git older than 1.8.4.3

.github/workflows/ci.yml
=> run GitHub actions for pull requests from forks

setup.py
Fixes #187 which was introduced in #183.
=> fix missing comma before vcs.fish

MANIFEST.in
=> add missing files to source archive

vcstool/clients/git.py
fix: https://github.com/dirk-thomas/vcstool/issues/205
=> Fix #205: `--recursive` is not recursive 

test/import.txt, test/import_shallow.txt, test/list.repos, test/test_commands.py, test/validate.txt, vcstool/clients/git.py
=> support git version starting with heads/ or tags/
